import React from 'react';
import { ArrowLeft, ArrowRight, ArrowDown, Shield, Activity, Database, Lock, Layers, Eye } from 'lucide-react';

const GithubIcon = ({ className }: { className?: string }) => (
  <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path>
  </svg>
);
import { motion } from 'motion/react';

interface Props {
  route: string;
}

/* ─────────── Shared UI Components ─────────── */
function SectionTitle({ title, subtitle }: { title: string; subtitle: string }) {
  return (
    <div className="mb-8">
      <h2 className="text-3xl font-semibold tracking-tight text-black mb-3" style={{ letterSpacing: '-0.03em' }}>{title}</h2>
      <p className="text-lg text-black/50 leading-relaxed max-w-2xl">{subtitle}</p>
    </div>
  );
}

function Card({ children, dark = false, span = 1 }: { children: React.ReactNode; dark?: boolean; span?: number }) {
  const baseStyle = "rounded-2xl p-7 md:p-9 flex flex-col h-full";
  const themeStyle = dark 
    ? "bg-[#1A1A2E] text-white" 
    : "bg-gray-50 border border-black/5 text-gray-900";
  const spanStyle = span === 2 ? "md:col-span-2" : "";
  
  return (
    <div className={`${baseStyle} ${themeStyle} ${spanStyle}`}>
      {children}
    </div>
  );
}

function CodeBlock({ children }: { children: string }) {
  return (
    <pre className="bg-white border border-black/8 rounded-xl p-5 font-mono text-[13px] text-black/70 overflow-x-auto whitespace-pre leading-relaxed shadow-sm mt-4">
      {children}
    </pre>
  );
}

/* ═══════════════════════════════════════════════════════════════════
   DOCUMENTATION PAGE
   ═══════════════════════════════════════════════════════════════════ */
function DocsContent() {
  return (
    <div className="space-y-24">
      
      {/* KEY TERMS */}
      <section>
        <SectionTitle 
          title="Key Terms & Metrics" 
          subtitle="Understanding the business and evaluation vocabulary used across the system." 
        />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card dark>
            <h3 className="text-xl font-semibold mb-4 text-white/90" style={{ letterSpacing: '-0.02em' }}>Business Operations</h3>
            <ul className="space-y-4 text-white/70 text-sm">
              <li><strong className="text-white">Review Rate:</strong> The percentage of total transactions flagged for manual review. At the v2.0.1 production threshold (0.035), we review only 0.76% of transactions, strictly limiting the operational burden on the fraud team.</li>
              <li><strong className="text-white">Cost-Based Threshold:</strong> An operational cutoff determined by balancing the financial cost of false positives against false negatives. By assuming an illustrative cost of ₹50 per false positive and ₹12,536 per missed fraud, we mathematically anchor our threshold decisions instead of guessing.</li>
              <li><strong className="text-white">Grounded Evidence:</strong> Natural language justification generated by an LLM strictly based on the statistical model's highest contributing features. This transforms an opaque risk score into a concrete narrative for the human analyst.</li>
              <li><strong className="text-white">Audit Trail:</strong> An immutable, chronological database record of every score and evidence generation step. This ensures decisions shown in the Dashboard remain verifiable for compliance and chargeback disputes.</li>
            </ul>
          </Card>
          <Card>
            <h3 className="text-xl font-semibold mb-4" style={{ letterSpacing: '-0.02em' }}>Evaluation Metrics</h3>
            <ul className="space-y-4 text-black/60 text-sm">
              <li><strong className="text-black/80">PR-AUC (Headline Metric):</strong> Measures the trade-off between precision and recall. Because our dataset has a highly imbalanced ~3.5% fraud rate, PR-AUC (0.1740 for v2.0.1) is our true headline metric, unlike ROC-AUC which masks false positives behind massive true negative counts.</li>
              <li><strong className="text-black/80">ROC-AUC:</strong> Measures the model's overall ability to rank fraud above legitimate transactions. Our v2.0.1 model achieves an 0.8100 ROC-AUC, demonstrating strong general discriminative power across all possible thresholds.</li>
              <li><strong className="text-black/80">Fraud Capture (Recall):</strong> The percentage of actual fraudulent transactions successfully flagged. At our v2.0.1 production threshold, we capture 7.62% of fraud (235 out of 3083 actual frauds), reflecting an explicit trade-off to maintain an ultra-low review rate.</li>
              <li><strong className="text-black/80">Precision:</strong> The percentage of flagged transactions that are actually fraud. Our v2.0.1 model achieves 34.86% precision, meaning roughly 1 in 3 reviewed alerts is a true positive.</li>
              <li><strong className="text-black/80">Calibration (Brier Score):</strong> Measures how well the model's output probabilities match real-world fraud rates. Isotonic calibration improved our v1.0.0 Brier score from 0.0603 to 0.0214, ensuring a score of "0.90" mathematically translates to a 90% real-world fraud probability.</li>
            </ul>
          </Card>
        </div>
      </section>

      {/* WHY */}
      <section>
        <SectionTitle 
          title="Why this exists" 
          subtitle="Fraud is an asymmetric war. Building a model that predicts it is easy; building a system that proves it and defends its boundaries is hard." 
        />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card dark>
            <Shield className="w-8 h-8 mb-6 text-white/80" />
            <h3 className="text-2xl font-semibold mb-4 leading-snug" style={{ letterSpacing: '-0.02em' }}>The Cost of False Positives</h3>
            <p className="text-white/70 text-base leading-relaxed">
              Every flagged transaction requires manual review or blocks a legitimate customer. We built this system to enforce an explicit business cost curve. A binary "fraud" or "not fraud" label is insufficient. This system maps calibrated probabilities to operational thresholds.
            </p>
          </Card>
          <Card>
            <Eye className="w-8 h-8 mb-6 text-black/40" />
            <h3 className="text-2xl font-semibold mb-4 leading-snug" style={{ letterSpacing: '-0.02em' }}>The Audit Gap</h3>
            <p className="text-black/60 text-base leading-relaxed">
              Black-box ML scores leave analysts guessing during chargeback disputes. We designed a dual-pipeline where statistical scoring is strictly separated from LLM-driven evidence generation, ensuring every high-risk score is backed by a verifiable, human-readable narrative.
            </p>
          </Card>
        </div>
      </section>

      {/* WHAT */}
      <section>
        <SectionTitle 
          title="What the system is" 
          subtitle="A production-ready pipeline combining temporal feature engineering, an XGBoost classifier, isotonic calibration, and a deterministic LLM agent." 
        />
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card span={2}>
            <Database className="w-8 h-8 mb-6 text-black/40" />
            <h3 className="text-2xl font-semibold mb-4" style={{ letterSpacing: '-0.02em' }}>The Dataset & Foundation</h3>
            <p className="text-black/60 text-base leading-relaxed mb-4">
              We trained on the IEEE-CIS Fraud Detection dataset. It contains 590,540 real e-commerce transactions with a realistic class imbalance of ~3.5% fraud.
            </p>
            <p className="text-black/60 text-base leading-relaxed">
              To prevent the most common failure mode in fraud models — target leakage — we enforced strict temporal splitting (earliest 70% train, next 15% validation, final 15% test). All historical features use strictly causal aggregations.
            </p>
          </Card>
          <Card dark>
            <Layers className="w-8 h-8 mb-6 text-white/80" />
            <h3 className="text-2xl font-semibold mb-4" style={{ letterSpacing: '-0.02em' }}>The Two Models</h3>
            <p className="text-white/70 text-sm leading-relaxed mb-4">
              <strong>v1.0.0 (462 features):</strong> Our research/offline model. It achieved ROC-AUC 0.9010 but relied on 339 undocumented proprietary V-columns. It is superseded by v2.0.1 in the deployed system.
            </p>
            <p className="text-white/70 text-sm leading-relaxed">
              <strong>v2.0.1 (20 features):</strong> The live-serving model. Engineered exclusively from 7 realistic form fields. We explicitly traded theoretical accuracy for operational viability.
            </p>
          </Card>
        </div>
      </section>

      {/* HOW */}
      <section>
        <SectionTitle 
          title="How it operates" 
          subtitle="The mechanics of strict leakage prevention and verifiable model outputs." 
        />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card>
            <h3 className="text-xl font-semibold mb-4" style={{ letterSpacing: '-0.02em' }}>Preventing Target Leakage</h3>
            <p className="text-black/60 text-base leading-relaxed">
              During development, we discovered that our <code>uid_prior_fraud_rate</code> feature implicitly assumed chargeback labels were instantaneously known. This target leakage artificially inflated PR-AUC from 0.49 to 0.64. We surgically dropped the feature and completely retrained the pipeline to ensure production behavior exactly matches evaluation metrics.
            </p>
          </Card>
          <Card>
            <h3 className="text-xl font-semibold mb-4" style={{ letterSpacing: '-0.02em' }}>Categorical Safety</h3>
            <p className="text-black/60 text-base leading-relaxed">
              Standard alphabetical encoding caused a severe train/serve skew where mapping integers were scrambled across splits. We deployed a custom fitted <code>CategoricalEncoder</code> that learns mappings strictly from the training split and loudly fails on invalid datatypes during live inference, guaranteeing data integrity.
            </p>
          </Card>
        </div>
      </section>

      {/* GLOSSARY */}
      <section>
        <SectionTitle 
          title="Feature Glossary" 
          subtitle="Understanding the raw inputs and engineered signals used by the live v2.0.1 model." 
        />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card>
            <h3 className="text-xl font-semibold mb-4" style={{ letterSpacing: '-0.02em' }}>Raw Form Inputs</h3>
            <ul className="space-y-4 text-black/60 text-base">
              <li><strong className="text-black/80">card1:</strong> An internal, anonymized token representing the card (not the actual PAN).</li>
              <li><strong className="text-black/80">card4:</strong> The network brand (e.g., Visa, Mastercard).</li>
              <li><strong className="text-black/80">card6:</strong> Funding type (Credit or Debit).</li>
              <li><strong className="text-black/80">TransactionDT:</strong> Seconds elapsed since an arbitrary reference date, used to derive temporal metrics, not a real timestamp.</li>
              <li><strong className="text-black/80">ProductCD:</strong> A coded category for the purchased product or service.</li>
            </ul>
          </Card>
          <Card dark>
            <h3 className="text-xl font-semibold mb-4 text-white/90" style={{ letterSpacing: '-0.02em' }}>Key Engineered Signals</h3>
            <ul className="space-y-4 text-white/70 text-sm">
              <li><strong className="text-white">card1_txn_count_1h/24h/7d:</strong> Velocity metrics tracking how often this specific card was used recently. High velocity indicates potential card-testing or a compromised credential.</li>
              <li><strong className="text-white">time_since_last_card1:</strong> Time elapsed since the card's last transaction. A high value (or maxed out value) means this is a newly seen or long-dormant card, increasing risk.</li>
              <li><strong className="text-white">amt_deviation_from_card1:</strong> How far the current amount deviates from this card's historical average. Extreme positive deviations signal potential account takeover.</li>
              <li><strong className="text-white">is_free_email:</strong> A boolean flag if the domain is a known free provider (e.g., gmail.com). A value of 1 slightly increases baseline risk compared to enterprise domains.</li>
              <li><strong className="text-white">card1_email_cooccurrence:</strong> Tracks how often this specific card has historically been paired with this exact email domain. A low co-occurrence frequency indicates a novel, unverified linkage.</li>
            </ul>
          </Card>
        </div>
      </section>

    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════
   ARCHITECTURE PAGE
   ═══════════════════════════════════════════════════════════════════ */
function ArchitectureContent() {
  return (
    <div className="space-y-24">
      
      {/* WHY */}
      <section>
        <SectionTitle 
          title="Why dual pipelines" 
          subtitle="Language models are powerful narrative engines but dangerous statistical classifiers. We isolate them completely from the decision boundary." 
        />
        <div className="grid grid-cols-1 gap-6">
          <Card dark>
            <div className="flex items-center gap-4 mb-6">
              <Lock className="w-8 h-8 text-[#ff4d4d]" />
              <span className="text-[#ff4d4d] font-semibold text-xs uppercase tracking-wider bg-[#ff4d4d]/10 px-3 py-1 rounded-full border border-[#ff4d4d]/20">The LLM Invariant</span>
            </div>
            <h3 className="text-2xl font-semibold mb-4 leading-snug" style={{ letterSpacing: '-0.02em' }}>The LLM Cannot Decide</h3>
            <p className="text-white/70 text-base leading-relaxed">
              The LLM cannot make the fraud decision. The XGBoost model decides. The LLM only produces structured evidence for transactions that were <em>already flagged</em> by the statistical model. This architectural constraint prevents the inherent unpredictability of language models from influencing binary business decisions.
            </p>
          </Card>
        </div>
      </section>

      {/* WHAT */}
      <section>
        <SectionTitle 
          title="What the architecture is" 
          subtitle="A deterministic, reconstructable chain of events mapping raw data to final actions." 
        />
        <div className="grid grid-cols-1 gap-6">
          <Card>
            <Activity className="w-8 h-8 mb-6 text-black/40" />
            <h3 className="text-2xl font-semibold mb-6" style={{ letterSpacing: '-0.02em' }}>The Decision Chain</h3>
            <div className="flex flex-col md:flex-row flex-wrap items-center justify-center gap-3 md:gap-4 p-8 md:p-12 bg-[#F5F5F5] rounded-3xl border border-black/5 mb-6">
              {['Raw Transaction', 'Input Validation', 'Feature Pipeline', 'XGBoost Model', 'Isotonic Calibration', 'Risk Probability', 'Cost-Based Threshold', 'PASS/FLAG'].map((step, i) => (
                <React.Fragment key={step}>
                  <span className="bg-white border border-black/10 text-black/80 text-sm md:text-base font-medium px-5 py-3 rounded-xl shadow-sm whitespace-nowrap">{step}</span>
                  {i < 7 && <ArrowRight className="hidden md:block w-5 h-5 text-black/30 shrink-0" />}
                  {i < 7 && <ArrowDown className="md:hidden w-5 h-5 text-black/30 shrink-0 my-1" />}
                </React.Fragment>
              ))}
              
              <div className="w-full h-px bg-black/10 my-4 md:my-6 relative">
                <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-[#F5F5F5] px-4 text-xs font-bold text-black/40 uppercase tracking-wider">If FLAG</div>
              </div>
              
              {['Evidence Agent', 'Audit Trail'].map((step, i) => (
                <React.Fragment key={step}>
                  <span className="bg-white border border-black/10 text-black/80 text-sm md:text-base font-medium px-5 py-3 rounded-xl shadow-sm whitespace-nowrap">{step}</span>
                  {i < 1 && <ArrowRight className="hidden md:block w-5 h-5 text-black/30 shrink-0" />}
                  {i < 1 && <ArrowDown className="md:hidden w-5 h-5 text-black/30 shrink-0 my-1" />}
                </React.Fragment>
              ))}
            </div>
            <p className="text-black/60 text-base leading-relaxed">
              An auditor can take any transaction and follow this chain end-to-end. Every intermediate value, including a cryptographic SHA-256 hash of the feature vector, is stored in the SQLite database to prove that the exact same features produced the exact same decision.
            </p>
          </Card>
        </div>
      </section>

      {/* HOW */}
      <section>
        <SectionTitle 
          title="How it executes" 
          subtitle="The mechanics of scoring, bounding, and grounding." 
        />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card>
            <h3 className="text-xl font-semibold mb-4" style={{ letterSpacing: '-0.02em' }}>The Scoring Pipeline</h3>
            <p className="text-black/60 text-base leading-relaxed mb-4">
              When a transaction hits the API, the system validates the 8 required fields via Pydantic. It transforms these inputs into 22 engineered features using pre-trained frequency maps loaded exclusively from the training set.
            </p>
            <p className="text-black/60 text-base leading-relaxed">
              XGBoost outputs a raw score, which passes through an isotonic regression model fitted on the validation set. This outputs a true, calibrated probability. We then compare this probability against a frozen 5.0% production threshold to emit the final PASS or FLAG decision.
            </p>
          </Card>
          <Card>
            <h3 className="text-xl font-semibold mb-4" style={{ letterSpacing: '-0.02em' }}>The Evidence Pipeline</h3>
            <p className="text-black/60 text-base leading-relaxed mb-4">
              For flagged transactions, the Context Builder constructs a rigid JSON block containing only the raw inputs and computed features. It sends this to the Groq API (temperature=0) to generate risk claims.
            </p>
            <p className="text-black/60 text-base leading-relaxed">
              The Grounding Validator then executes. It programmatically checks that every field cited in the LLM's claim actually exists in the provided context, and that the cited values match exactly. If the LLM hallucinates a field or alters a value, the entire evidence packet is rejected and logged as a failure.
            </p>
          </Card>
        </div>
      </section>

    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════
   API PAGE
   ═══════════════════════════════════════════════════════════════════ */
function ApiContent() {
  return (
    <div className="space-y-24">
      
      <section>
        <SectionTitle 
          title="Evidence API Reference" 
          subtitle="A complete RESTful interface for the risk pipeline." 
        />
        <div className="grid grid-cols-1 gap-6">
          
          <Card span={2}>
            <h3 className="text-xl font-semibold mb-2 flex items-center gap-3">
              <span className="bg-black text-white text-[10px] font-bold px-2 py-1 rounded">POST</span>
              /score
            </h3>
            <p className="text-black/60 text-base mb-6">Computes the calibrated fraud risk probability for a single transaction using the live v2.0.1 model.</p>
            
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div>
                <div className="text-[11px] font-bold text-black/40 uppercase tracking-wider mb-2">Request Body</div>
                <CodeBlock>{`{
  "TransactionID": 1000001,
  "TransactionDT": 86400,
  "TransactionAmt": 150.00,
  "ProductCD": "W",
  "card1": 4000,
  "card4": "visa",
  "card6": "debit",
  "P_emaildomain": "gmail.com"
}`}</CodeBlock>
              </div>
              <div>
                <div className="text-[11px] font-bold text-black/40 uppercase tracking-wider mb-2">Response (200 OK)</div>
                <CodeBlock>{`{
  "transaction_id": 1000001,
  "risk_probability": 0.0469,
  "threshold": 0.05,
  "decision": "PASS",
  "model_version": "v2.0.1",
  "calibration_version": "v2.0.1",
  "feature_pipeline_version": "v2.0.1"
}`}</CodeBlock>
              </div>
            </div>
          </Card>

          <Card span={2}>
            <h3 className="text-xl font-semibold mb-2 flex items-center gap-3">
              <span className="bg-black text-white text-[10px] font-bold px-2 py-1 rounded">POST</span>
              /evidence/&#123;id&#125;
            </h3>
            <p className="text-black/60 text-base mb-6">Generates grounded LLM evidence for a flagged transaction. Fails with 400 Bad Request if called on a transaction with a PASS decision.</p>
            
            <div className="text-[11px] font-bold text-black/40 uppercase tracking-wider mb-2">Response (200 OK)</div>
            <CodeBlock>{`{
  "transaction_id": 1000001,
  "status": "generated",
  "summary": "Transaction flagged due to unusual amount...",
  "evidence": [
    {
      "claim": "Transaction amount ($500) deviates significantly...",
      "sources": ["TransactionAmt", "amt_deviation_from_card1"],
      "source_values": { "TransactionAmt": 500.0, "amt_deviation_from_card1": 2.34 }
    }
  ],
  "grounding_valid": true
}`}</CodeBlock>
          </Card>

        </div>
      </section>



    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════
   MAIN INFO PAGE LAYOUT
   ═══════════════════════════════════════════════════════════════════ */
export default function InfoPage({ route }: Props) {
  const pages: Record<string, { title: string; subtitle: string; content: () => React.ReactNode }> = {
    '#docs': {
      title: 'Documentation',
      subtitle: 'The dataset, models, and pipeline behind the Scorer.',
      content: DocsContent,
    },
    '#api': {
      title: 'Evidence API',
      subtitle: 'Endpoints for scoring, evidence, and audit trails.',
      content: ApiContent,
    },
    '#architecture': {
      title: 'System Architecture',
      subtitle: 'The decision chain and LLM isolation strategy.',
      content: ArchitectureContent,
    },
  };

  const page = pages[route] || pages['#docs'];
  const ContentComponent = page.content;

  return (
    <div className="min-h-screen bg-[#F5F5F5] text-gray-900 font-['Inter'] selection:bg-black/10 relative overflow-x-hidden pb-24">

      {/* Navbar */}
      <header className="fixed top-0 w-full z-50 bg-white/80 backdrop-blur-xl border-b border-black/8 flex items-center justify-between px-6 md:px-10 h-16">
        <button
          onClick={() => window.location.hash = ''}
          className="flex items-center gap-2 text-black/50 hover:text-black transition-colors text-sm font-medium"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </button>
        <nav className="hidden md:flex items-center gap-6">
          {[
            { hash: '#docs', label: 'Docs' },
            { hash: '#api', label: 'API' },
            { hash: '#architecture', label: 'Architecture' },
          ].map(link => (
            <a
              key={link.hash}
              href={link.hash}
              className={`text-sm font-medium transition-colors px-3 py-1.5 rounded ${route === link.hash ? 'text-black bg-black/5' : 'text-black/50 hover:text-black hover:bg-black/5'}`}
            >
              {link.label}
            </a>
          ))}
        </nav>
        <div className="flex items-center gap-4">
          <a href="https://github.com/loomking/fraud-risk-scorer" target="_blank" rel="noopener noreferrer" className="text-black/50 hover:text-black transition-colors hidden md:block">
            <GithubIcon className="w-5 h-5" />
          </a>
          <button
          onClick={() => window.location.hash = '#dashboard'}
          className="bg-black text-white text-sm font-medium px-5 py-2 rounded-full hover:bg-gray-800 transition-colors"
        >
          Launch Dashboard
        </button>
        </div>
      </header>

      {/* Hero Header */}
      <div className="pt-32 pb-12 px-6 md:px-10 max-w-5xl mx-auto text-center">
        <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
          <h1 className="text-4xl md:text-5xl font-semibold tracking-tight text-black mb-4" style={{ letterSpacing: '-0.03em' }}>{page.title}</h1>
          <p className="text-lg text-black/50 leading-relaxed max-w-xl mx-auto">{page.subtitle}</p>
        </motion.div>
      </div>

      {/* Content */}
      <motion.main
        key={route}
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.1 }}
        className="max-w-5xl mx-auto px-6 md:px-10"
      >
        <ContentComponent />
      </motion.main>

      {/* ─── Footer ─── */}
      <footer className="bg-[#F5F5F5] border-t border-black/10 px-6 py-8 mt-12">
        <div className="max-w-[88rem] mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <Shield className="w-5 h-5 text-black/40" />
            <span className="text-sm text-black/40 font-medium">Fraud Risk Scorer · v2.0.1</span>
          </div>
          <div className="flex items-center gap-6 text-sm text-black/40">
            <a href="https://github.com/loomking/fraud-risk-scorer" target="_blank" rel="noopener noreferrer" className="hover:text-black transition-colors">
              <GithubIcon className="w-4 h-4" />
            </a>
            <a href="#docs" className="hover:text-black transition-colors">Docs</a>
            <a href="#api" className="hover:text-black transition-colors">API</a>
            <a href="#architecture" className="hover:text-black transition-colors">Architecture</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
